# @package training
# Ref: https://github.com/chrischoy/SpatioTemporalSegmentation/blob/master/config.py
epochs: 20
num_workers: 64
batch_size: 8
shuffle: False
cuda: 0
precompute_multi_scale: False # Compute multiscate features on cpu for faster training / inference
enable_mixed: True # Allow mixed precision on supported models
optim:
  base_lr: 0.1
  # accumulated_gradient: -1 # Accumulate gradient accumulated_gradient * batch_size
  grad_clip: -1
  optimizer:
    class: SGD
    params:
      lr: ${training.optim.base_lr} # The path is cut from training
      weight_decay: 1e-4
      momentum: 0.9
      dampening: 0.1
  lr_scheduler: ${lr_scheduler}
  bn_scheduler:
    bn_policy: "step_decay"
    params:
      bn_momentum: 0.1
      bn_decay: 0.2
      decay_step: 200
      bn_clip: 2e-2
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: ""

# Those arguments within experiment defines which model, dataset and task to be created for benchmarking
# parameters for Weights and Biases
wandb:
  project: COPC-ground-v${data.dataset_version}
  log: True
  name: ${model_name}
  public: True # It will be display the model within wandb log, else not.
  config:
    resolution: ${data.resolution}
    model_name: ${model_name}
    number_of_sample_per_epoch: ${data.number_of_sample_per_epoch}
    training_classes_weights: ${data.training_classes_weights}

  # parameters for TensorBoard Visualization
tensorboard:
  log: False
